name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to ACR
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push image
      - name: Build and push image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/exam-reminder:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/exam-reminder:${{ github.sha }}

      # DEPLOY (STUDENT ACCOUNT)
      - name: Deploy to Azure Container App
        run: |
          curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.AZURE_CONTAINERAPP_TOKEN }}" \
          -H "Content-Type: application/json" \
          https://management.azure.com/subscriptions/${{ secrets.AZURE_SUB_ID }}/resourceGroups/exam-reminder-rg/providers/Microsoft.App/containerApps/exam-reminder-app?api-version=2024-02-02-preview \
          -d '{
                "properties": {
                  "template": {
                    "containers": [
                      {
                        "name": "exam-reminder-app",
                        "image": "${{ secrets.ACR_LOGIN_SERVER }}/exam-reminder:${{ github.sha }}"
                      }
                    ]
                  }
                }
              }'
